version: '3.1'

services:
    rabbitmq:
        image: rabbitmq:3-management
        networks: 
            - supplier_network
        ports:
            - 5672:5672
            - 15672:15672
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        networks: 
            - supplier_network
    supplier_service:
        restart: always
        build:
            context: .
            dockerfile: ./Supplier.Dockerfile
        networks: 
            - supplier_network
        ports:
            - 8080:3000
        depends_on: 
            - "rabbitmq"
            - "mongo"
        volumes: 
            - mongo-db-config:/data/configdb
            - mongo-db-data:/data/db
networks: 
    supplier_network:
        driver: bridge

volumes: 
    mongo-db-config:
    mongo-db-data: