version: '2'
services:
  stock_service:
    build:
          context: .
          dockerfile: Stock.Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
